name: CI
on:
  push:
    branches:
      - main
      - develop*
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - develop*
    paths-ignore:
      - '**.md'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: 'pip'
          cache-dependency-path: setup.cfg

      - name: Install Python packages
        run: |
          pip install .
          pip install ".[lint]"

      - name: Run isort
        run: isort --verbose --check --diff modflow_devtools

      - name: Run black
        run: black --check --diff modflow_devtools

      - name: Run flake8
        run: flake8 --count --show-source --exit-zero modflow_devtools

      - name: Run pylint
        run: pylint --jobs=0 --errors-only --exit-zero modflow_devtools
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Upgrade pip and install build and twine
        run: |
          pip install --upgrade pip
          pip install build twine

      - name: Base modflow_devtools installation
        run: |
          pip --verbose install .

      - name: Print package version
        run: |
          python -c "import modflow_devtools; print(modflow_devtools.__version__)"

      - name: Build package
        run: |
          python -m build
      
      - name: Check distribution
        run: |
          twine check --strict dist/*

  test:
    name: Test
    needs:
      - build
      - lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
        python: [ 3.7, 3.8, 3.9, "3.10" ]
    env:
      GCC_V: 11
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: modflow-devtools
      
      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6
          path: modflow6
      
      - name: Checkout modflow6 examples
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-examples
          path: modflow6-examples
      
      - name: Checkout modflow6 test models
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-testmodels
          path: modflow6-testmodels
      
      - name: Checkout modflow6 large test models
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-largetestmodels
          path: modflow6-largetestmodels

      - name: Install executables
        uses: modflowpy/install-modflow-action@v1

      - name: Setup GNU Fortran ${{ env.GCC_V }}
        uses: awvwgk/setup-fortran@main
        with:
          compiler: gcc
          version: ${{ env.GCC_V }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: |
            modflow-devtools/setup.cfg
            modflow6-examples/etc/requirements*.txt

      - name: Install Python packages
        working-directory: modflow-devtools
        run: |
          pip install .
          pip install ".[test]"
      
      - name: Cache modflow6 examples
        id: cache-examples
        uses: actions/cache@v3
        with:
          path: modflow6-examples/examples
          key: modflow6-examples-${{ hashFiles('modflow6-examples/data/**') }}
      
      - name: Install extra Python packages
        # can't build examples on Python 3.7, requires Python 3.8
        if: steps.cache-examples.outputs.cache-hit != 'true' && matrix.python != '3.7'
        working-directory: modflow6-examples/etc
        run: |
          pip install -r requirements.pip.txt
          pip install -r requirements.usgs.txt

      - name: Build modflow6 example models
        # can't build examples on Python 3.7, requires Python 3.8
        if: steps.cache-examples.outputs.cache-hit != 'true' && matrix.python != '3.7'
        working-directory: modflow6-examples/etc
        run: python ci_build_files.py

      - name: Run tests
        working-directory: modflow-devtools
        env:
          BIN_PATH: ~/.local/bin/modflow
          REPOS_PATH: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pytest -v -n auto --durations 0